### ISSUE TITLE
How to add wwwroot folder to staticfile as in windows services hosing?

### ISSUE THREAD

**Issue by bobbydog** [dotnet/AspNetCore.Docs.zh-cn#269]
[在此处输入反馈]
文档里说 Windows Service里默认了ContentRoot不需要修改即可在服务.exe的目录下读取配置文件,但是 网站的静态文件 如 wwwroot, 要如何加入到 StaticFiles里?

app.UseStaticFiles(new StaticFileOptions()
            {
                FileProvider = new PhysicalFileProvider(Path.Combine(env.ContentRootPath, "wwwroot")),
                RequestPath = new PathString("")
            });
这样是提示找不到文件
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\hrst\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:11000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\batrun\batservice\webservice
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:11000/web/login
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Hrst.AIDetect.WebApiServer.HomeController (Hrst.AIDetect.PCWeb).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Hrst.AIDetect.WebApiServer.HomeController.Index (Hrst.AIDetect.PCWeb) in 31.3317ms
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLVTBPDN7OPS", Request id "0HLVTBPDN7OPS:00000001": An unhandled exception was thrown by the application.
System.IO.FileNotFoundException: Could not find file 'C:\Users\hrst\AppData\Local\Temp\.net\Hrst.AIDetect.PCWeb\qpu1dfz5.zr3\wwwroot\index.html'.
File name: 'C:\Users\hrst\AppData\Local\Temp\.net\Hrst.AIDetect.PCWeb\qpu1dfz5.zr3\wwwroot\index.html'
   at System.IO.FileInfo.get_Length()
   at Microsoft.AspNetCore.Mvc.Infrastructure.PhysicalFileResultExecutor.GetFileInfo(String path)
   at Microsoft.AspNetCore.Mvc.Infrastructure.PhysicalFileResultExecutor.ExecuteAsync(ActionContext context, PhysicalFileResult result)
   at Microsoft.AspNetCore.Mvc.PhysicalFileResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 1693.676ms 500

事件查看器里的错误
Category: Microsoft.AspNetCore.Server.Kestrel EventId: 13 ConnectionId: 0HLVTDBSPCQ5P RequestId: 0HLVTDBSPCQ5P:00000001 RequestPath: / SpanId: |22a84b5c-4b6ecda9adb52676. TraceId: 22a84b5c-4b6ecda9adb52676 ParentId: Connection id "0HLVTDBSPCQ5P", Request id "0HLVTDBSPCQ5P:00000001": An unhandled exception was thrown by the application. Exception: System.IO.FileNotFoundException: Could not find file 'C:\Windows\TEMP\.net\Hrst.AIDetect.PCWeb\rcy1c4qq.4kx\wwwroot\index.html'. File name: 'C:\Windows\TEMP\.net\Hrst.AIDetect.PCWeb\rcy1c4qq.4kx\wwwroot\index.html' at System.IO.FileInfo.get_Length() at 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [在 Windows 服务中托管 ASP.NET Core](https://docs.microsoft.com/zh-cn/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @bobbydog
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @bobbydog 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles. 

Microsoft DOCS International Team
