### ISSUE TITLE
Value cannot be null. (Parameter 'programType')

### ISSUE THREAD

**Issue by SincereZheng** [dotnet/AspNetCore.Docs.zh-cn#346]
[当添加“使用实体框架生成Razor页面(CRUD)”时报这个错：Finding the generator 'razorpage'...
Running the generator 'razorpage'...
Generating a new DbContext class 'MyCoreApp2.Data.RazorPagesMovieContext'
Value cannot be null. (Parameter 'programType')
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [第 2 部分，添加模型](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by SincereZheng** [comment]
![image](https://user-images.githubusercontent.com/30676910/103333847-43f5a580-4aaa-11eb-8c97-b2acb4bc0b61.png)
